package frontend;

import backend.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FrmTransaksi
     */
    public FrmTransaksi() {
        initComponents();
        tampilkanData();
        kosongkanForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnomor = new javax.swing.JTextField();
        txtkodetransaksi = new javax.swing.JTextField();
        txtnamapembeli = new javax.swing.JTextField();
        txtkodeobat = new javax.swing.JTextField();
        txtnamaobat = new javax.swing.JTextField();
        txtmerek = new javax.swing.JTextField();
        txthargajual = new javax.swing.JTextField();
        txtjumlahbeli = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableobat = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletransaksi = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DATA TRANSAKSI");

        jLabel2.setText("Nomor");

        jLabel3.setText("Kode Transaksi");

        jLabel4.setText("Nama Pembeli");

        jLabel5.setText("Kode Obat");

        jLabel6.setText("Nama Obat");

        jLabel7.setText("Merek");

        jLabel8.setText("Harga Jual");

        jLabel9.setText("Jumlah Beli");

        jLabel10.setText("Tanggal");

        jLabel11.setText("Total");

        txtnomor.setEnabled(false);

        txtmerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmerekActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        tableobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableobatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableobat);

        tabletransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabletransaksi);

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel13.setText("Search");

        jTextField12.setText("Id Obat");
        jTextField12.setEnabled(false);

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali ke Menu Utama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtkodetransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(txtnomor)
                                .addComponent(txtnamapembeli)
                                .addComponent(txtkodeobat)
                                .addComponent(txtnamaobat)
                                .addComponent(txtmerek))
                            .addGap(34, 34, 34))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txttanggal)
                            .addGap(29, 29, 29)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtkodetransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtkodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnamaobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah)
                    .addComponent(btnhapus)
                    .addComponent(btnsimpan))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableobatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableobatMouseClicked

    private void tabletransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabletransaksi.getModel();
            int row = tabletransaksi.getSelectedRow();
            transaksi tr = new transaksi();
            
            tr = transaksi.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
            txtnomor.setText(Integer.toString(tr.getNomor()));
            txtkodetransaksi.setText(tr.getKode_transaksi());
            txtnamapembeli.setText(tr.getNama_pembeli());
            txtkodeobat.setText(tr.getKode_obat());
            txtnamaobat.setText(tr.getNama_obat());
            txtmerek.setText(tr.getMerek_obat());
            txthargajual.setText(Integer.toString(tr.getHarga_jual()));
            txtjumlahbeli.setText(Integer.toString(tr.getJumlah_beli()));
            txttanggal.setText(tr.getTanggal_transaksi());
            txttotal.setText(Integer.toString(tr.getTotal_harga()));
    }//GEN-LAST:event_tabletransaksiMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabletransaksi.getModel();
        int row = tabletransaksi.getSelectedRow();
        
        transaksi tr = new transaksi().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        tr.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        cari(txtcari.getText());
    }//GEN-LAST:event_btncariActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String kode = txtkodetransaksi.getText();
        String namapembeli = txtnamapembeli.getText();
        String kodeobat = txtkodeobat.getText();
        String namaobat = txtnamaobat.getText();
        String merek = txtmerek.getText();
        String hargajual = txthargajual.getText();
        String jumlahbeli = txtjumlahbeli.getText();
        String tanggal = txttanggal.getText();
        String total = txttotal.getText();
        
        if(!(kode.isEmpty() && namapembeli.isEmpty() && kodeobat.isEmpty() && namaobat.isEmpty() && merek.isEmpty() && hargajual.isEmpty() && jumlahbeli.isEmpty() && tanggal.isEmpty() && total.isEmpty())){
            transaksi tr = new transaksi();
            tr.setNomor(Integer.parseInt(txtnomor.getText()));
            tr.setKode_transaksi(kode);
            tr.setNama_pembeli(namapembeli);
            tr.setKode_obat(kodeobat);
            tr.setNama_obat(namaobat);
            tr.setMerek_obat(merek);
            tr.setHarga_jual(Integer.parseInt(txthargajual.getText()));
            tr.setJumlah_beli(Integer.parseInt(txtjumlahbeli.getText()));
            tr.setTotal_harga(Integer.parseInt(txttotal.getText()));
            tr.setTanggal_transaksi(tanggal);
            tr.save();
            
            tampilkanData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Silahkan lengkapi semua data");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuUtama menu = new MenuUtama();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmerekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTable tableobat;
    private javax.swing.JTable tabletransaksi;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtkodeobat;
    private javax.swing.JTextField txtkodetransaksi;
    private javax.swing.JTextField txtmerek;
    private javax.swing.JTextField txtnamaobat;
    private javax.swing.JTextField txtnamapembeli;
    private javax.swing.JTextField txtnomor;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    public void kosongkanForm() {
        txtnomor.setText("0");
        txtkodetransaksi.setText("");
        txtnamapembeli.setText("");
        txtkodeobat.setText("");
        txtnamaobat.setText("");
        txtmerek.setText("");
        txthargajual.setText("");
        txtjumlahbeli.setText("");
        txttanggal.setText("");
        txttotal.setText("");
    }

    public void tampilkanData() {
        Object[] namaKolom = new Object[] {"nomor", "kode_transaksi", "nama_pembeli", "kode_obat", "nama_obat", "merek_obat", "harga_jual", "jumlah_beli", "total_harga", "tanggal_transaksi"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(namaKolom);
        //int nomor, String kode_transaksi, String nama_pembeli, String kode_obat, String nama_obat, String merek_obat, String harga_jual, String jumlah_beli, String total_harga, String tanggal_transaksi
        ArrayList<transaksi> listTransaksi = transaksi.getAll();
        Object[] rowData = new Object[10];
        
        for (transaksi tr : listTransaksi){
            rowData[0] = tr.getNomor();
            rowData[1] = tr.getKode_transaksi();
            rowData[2] = tr.getNama_pembeli();
            rowData[3] = tr.getKode_obat();
            rowData[4] = tr.getNama_obat();
            rowData[5] = tr.getMerek_obat();
            rowData[6] = tr.getHarga_jual();
            rowData[7] = tr.getJumlah_beli();
            rowData[8] = tr.getTotal_harga();
            rowData[9] = tr.getTanggal_transaksi();
            
            model.addRow(rowData);
        }
        
        tabletransaksi.setModel(model);
        
        String[] kolom = {"Id_obat", "kode_obat", "nama_obat", "kategori_obat", "jenis_obat", "merek_obat", "harga_beli", "harga_jual", "jumlah_obat", "tanggal_masuk", "expired"};
        ArrayList<obat> list = new obat().getAll();
        Object rowDatas[] = new Object[11];
        
        tableobat.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (int i = 0; i < list.size(); i++){
            rowDatas[0] = list.get(i).getId_obat();
            rowDatas[1] = list.get(i).getKode_obat();
            rowDatas[2] = list.get(i).getNama_obat();
            rowDatas[3] = list.get(i).getKategori().getNama();
            rowDatas[4] = list.get(i).getJenis_obat();
            rowDatas[5] = list.get(i).getMerek_obat();
            rowDatas[6] = list.get(i).getHarga_beli_obat();
            rowDatas[7] = list.get(i).getHarga_jual_obat();
            rowDatas[8] = list.get(i).getJumlah_obat();
            rowDatas[9] = list.get(i).getTanggal_masuk();
            rowDatas[10] = list.get(i).getExpired();
            
            ((DefaultTableModel)tableobat.getModel()).addRow(rowDatas);
        }
    }
    
    public void cari(String keyword){
        String[] kolom = {"Id_obat", "kode_obat", "nama_obat", "kategori_obat", "jenis_obat", "merek_obat", "harga_beli", "harga_jual", "jumlah_obat", "tanggal_masuk", "expired"};
        ArrayList<obat> list = new obat().search(keyword);
        Object rowData[] = new Object[11];
        
        tableobat.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (obat ob : list){
            rowData[0] = ob.getId_obat();
            rowData[1] = ob.getKode_obat();
            rowData[2] = ob.getNama_obat();
            rowData[3] = ob.getKategori().getNama();
            rowData[4] = ob.getJenis_obat();
            rowData[5] = ob.getMerek_obat();
            rowData[6] = ob.getHarga_beli_obat();
            rowData[7] = ob.getHarga_jual_obat();
            rowData[8] = ob.getJumlah_obat();
            rowData[9] = ob.getTanggal_masuk();
            rowData[10] = ob.getExpired();
            
            ((DefaultTableModel)tableobat.getModel()).addRow(rowData);
        }
    }
}
