/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class FrmObat extends javax.swing.JFrame {

    /**
     * Creates new form FrmObat
     */
    public FrmObat() {
        initComponents();
        tampilkanData();
        tampilkanCmbKategori();
        kosongkanForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableobat = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkodeobat = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtmerek = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txthargabeli = new javax.swing.JTextField();
        txthargajual = new javax.swing.JTextField();
        txtjumlahstok = new javax.swing.JTextField();
        txttglmasuk = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtexpired = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtidobat = new javax.swing.JTextField();
        cmbkategori = new javax.swing.JComboBox<>();
        menu_utama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DATA OBAT");

        tableobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableobatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableobat);

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode Obat");

        jLabel3.setText("Nama");

        jLabel4.setText("Kategori");

        jLabel5.setText("Jenis");

        jLabel6.setText("Merek");

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga Beli");

        jLabel8.setText("Harga Jual");

        jLabel9.setText("Jumlah Stok");

        jLabel10.setText("Tanggal Masuk");

        jLabel11.setText("Search");

        jTextField10.setText("Id Obat or nama obat");
        jTextField10.setEnabled(false);

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel12.setText("Expired");

        jLabel13.setText("ID Obat");

        txtidobat.setEnabled(false);

        cmbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        menu_utama.setText("Menu Utama");
        menu_utama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_utamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtkodeobat, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtidobat))
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(cmbkategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjenis)
                                    .addComponent(txtmerek))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(btnsimpan))
                                        .addGap(46, 46, 46)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtjumlahstok, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txthargabeli)
                                    .addComponent(txthargajual)
                                    .addComponent(txttglmasuk)
                                    .addComponent(txtexpired, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGap(267, 267, 267)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncari)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(menu_utama)
                                .addGap(378, 378, 378)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 109, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(menu_utama))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnhapus)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtidobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkodeobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtjumlahstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txttglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtexpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableobatMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableobat.getModel();
        int row = tableobat.getSelectedRow();
        obat ob = new obat();
        
        ob = obat.getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        
        txtidobat.setText(Integer.toString(ob.getId_obat()));
        txtkodeobat.setText(ob.getKode_obat());
        txtnama.setText(ob.getNama_obat());
        cmbkategori.getModel().setSelectedItem(ob.getKategori());
        txtjenis.setText(ob.getJenis_obat());
        txtmerek.setText(ob.getMerek_obat());
        txthargabeli.setText(Integer.toString(ob.getHarga_beli_obat()));
        txthargajual.setText(Integer.toString(ob.getHarga_jual_obat()));
        txtjumlahstok.setText(Integer.toString(ob.getJumlah_obat()));
        txttglmasuk.setText(ob.getTanggal_masuk());
        txtexpired.setText(ob.getExpired());
    }//GEN-LAST:event_tableobatMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        //txtkodeobat.setText("0");
        //txtnama.setText("");
        //txtkategori.setText("");
       // txtjenis.setText("");
       // txtmerek.setText("");
       // txthargabeli.setText("");
       // txthargajual.setText("");
       // txtjumlahstok.setText("");
       // txttglmasuk.setText("");
       // txtexpired.setText("");
        String kode = txtkodeobat.getText();
        String nama = txtnama.getText();
        String jenis = txtjenis.getText();
        String merek = txtmerek.getText();
        String hargabeli = txthargabeli.getText();
        String hargajual = txthargajual.getText();
        String stok = txtjumlahstok.getText();
        String tglmasuk = txttglmasuk.getText();
        String expired = txtexpired.getText();
        
        if(!(kode.isEmpty() && nama.isEmpty() && jenis.isEmpty() && merek.isEmpty() && hargabeli.isEmpty() && hargajual.isEmpty() && stok.isEmpty() && tglmasuk.isEmpty() && expired.isEmpty())){
            obat ob = new obat();
            ob.setId_obat(Integer.parseInt(txtidobat.getText()));
            ob.setKode_obat(kode);
            ob.setNama_obat(nama);
            ob.setKategori((kategori)cmbkategori.getSelectedItem());
            ob.setJenis_obat(jenis);
            ob.setMerek_obat(merek);
            ob.setHarga_beli_obat(Integer.parseInt(txthargabeli.getText()));
            ob.setHarga_jual_obat(Integer.parseInt(txthargajual.getText()));
            ob.setJumlah_obat(Integer.parseInt(txtjumlahstok.getText()));
            ob.setTanggal_masuk(tglmasuk);
            ob.setExpired(expired);
            ob.save();
            
            //ob.setId_obat(rs.getInt("id_obat"));
                //ob.setKode_obat(rs.getString("kode_obat"));
               // ob.setNama_obat(rs.getString("nama_obat"));
               // ob.setKategori_obat(rs.getString("kategori_obat"));
               // ob.setJenis_obat(rs.getString("jenis_obat"));
               // ob.setMerek_obat(rs.getString("merek_obat"));
              //  ob.setHarga_beli_obat(rs.getInt("harga_beli_obat"));
              //  ob.setHarga_jual_obat(rs.getInt("harga_jual_obat"));
               // ob.setJumlah_obat(rs.getInt("jumlah_obat"));
               // ob.setTanggal_masuk(rs.getString("tanggal_masuk"));
               // ob.setExpired(rs.getString("expired"));
            
            tampilkanData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Silahkan lengkapi semua data");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        cari(txtcari.getText());
    }//GEN-LAST:event_btncariActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tableobat.getModel();
        int row = tableobat.getSelectedRow();
        
        obat ob = new obat().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        ob.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void menu_utamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_utamaActionPerformed
        MenuUtama menu = new MenuUtama();
        menu.setVisible(true);
    }//GEN-LAST:event_menu_utamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JButton menu_utama;
    private javax.swing.JTable tableobat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtexpired;
    private javax.swing.JTextField txthargabeli;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtidobat;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjumlahstok;
    private javax.swing.JTextField txtkodeobat;
    private javax.swing.JTextField txtmerek;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttglmasuk;
    // End of variables declaration//GEN-END:variables
    
    public void kosongkanForm() {
        txtidobat.setText("0");
        txtkodeobat.setText("");
        txtnama.setText("");
        cmbkategori.setSelectedIndex(0);
        txtjenis.setText("");
        txtmerek.setText("");
        txthargabeli.setText("");
        txthargajual.setText("");
        txtjumlahstok.setText("");
        txttglmasuk.setText("");
        txtexpired.setText("");
    }

    public void tampilkanData() {
        String[] kolom = {"Id_obat", "kode_obat", "nama_obat", "kategori_obat", "jenis_obat", "merek_obat", "harga_beli", "harga_jual", "jumlah_obat", "tanggal_masuk", "expired"};
        ArrayList<obat> list = new obat().getAll();
        Object rowData[] = new Object[11];
        
        tableobat.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (int i = 0; i < list.size(); i++){
            rowData[0] = list.get(i).getId_obat();
            rowData[1] = list.get(i).getKode_obat();
            rowData[2] = list.get(i).getNama_obat();
            rowData[3] = list.get(i).getKategori().getNama();
            rowData[4] = list.get(i).getJenis_obat();
            rowData[5] = list.get(i).getMerek_obat();
            rowData[6] = list.get(i).getHarga_beli_obat();
            rowData[7] = list.get(i).getHarga_jual_obat();
            rowData[8] = list.get(i).getJumlah_obat();
            rowData[9] = list.get(i).getTanggal_masuk();
            rowData[10] = list.get(i).getExpired();
            
            ((DefaultTableModel)tableobat.getModel()).addRow(rowData);
        }
    }
    
    public void cari(String keyword){
        String[] kolom = {"Id_obat", "kode_obat", "nama_obat", "kategori_obat", "jenis_obat", "merek_obat", "harga_beli", "harga_jual", "jumlah_obat", "tanggal_masuk", "expired"};
        ArrayList<obat> list = new obat().search(keyword);
        Object rowData[] = new Object[11];
        
        tableobat.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (obat ob : list){
            rowData[0] = ob.getId_obat();
            rowData[1] = ob.getKode_obat();
            rowData[2] = ob.getNama_obat();
            rowData[3] = ob.getKategori().getNama();
            rowData[4] = ob.getJenis_obat();
            rowData[5] = ob.getMerek_obat();
            rowData[6] = ob.getHarga_beli_obat();
            rowData[7] = ob.getHarga_jual_obat();
            rowData[8] = ob.getJumlah_obat();
            rowData[9] = ob.getTanggal_masuk();
            rowData[10] = ob.getExpired();
            
            ((DefaultTableModel)tableobat.getModel()).addRow(rowData);
        }
    }

    private void tampilkanCmbKategori() {
        cmbkategori.setModel(new DefaultComboBoxModel(new kategori().getAll().toArray()));
    }
}
